services:
  retroarch-web:
    image: inglebard/retroarch-web:latest
    container_name: retroarch-web
    ports:
      - "8080:80"  # Accès via le port 8080 dans le navigateur
    volumes:
      - ./roms:/roms  # Monte ton dossier local des ROMs dans le conteneur
    restart: unless-stopped
